In [220]:
%matplotlib inline
import pandas as pd
import matplotlib.pylab as plt
import numpy as np
from glob import glob

In [221]:
# csv 파일 로드
crime15 = pd.read_csv('crime15.csv', encoding = 'UTF-8', header=None)
crime15

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,경찰서별,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015
1,경찰서별,합계,합계,강력범,강력범,절도범,절도범,폭력범,폭력범,지능범,지능범,풍속범,풍속범,기타형사범,기타형사범,특별법범,특별법범
2,경찰서별,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
3,합계,56928,46673,694,657,5965,3740,9830,8670,7921,6360,259,237,3072,2826,29187,24183
4,강원청,0,478,0,69,0,0,0,17,0,109,0,7,0,6,0,270
5,춘천경찰서,10603,8162,115,96,1131,640,1631,1421,1214,906,31,22,530,452,5951,4625
6,원주경찰서,14088,11076,154,137,1779,918,2481,2113,1812,1348,53,47,633,592,7176,5921
7,강릉경찰서,7634,6060,108,82,829,443,1624,1365,1075,915,22,19,500,467,3476,2769
8,동해경찰서,3632,3060,43,44,290,200,752,689,434,371,13,12,178,178,1922,1566
9,태백경찰서,1484,1310,16,13,131,87,306,294,230,204,4,2,82,81,715,629
10,속초경찰서,4843,3928,43,38,439,282,916,791,738,621,26,25,265,245,2416,1926
11,삼척경찰서,2587,2179,32,24,196,127,529,496,348,287,11,11,142,139,1329,1095
12,홍천경찰서,2395,2176,50,44,188,262,335,336,319,254,13,12,146,130,1344,1138
13,횡성경찰서,1368,1059,22,19,155,102,173,152,165,109,11,10,83,80,759,587
14,영월경찰서,1038,896,15,9,88,44,161,139,152,134,7,7,83,71,532,492
15,평창경찰서,1400,1237,19,19,147,199,182,163,288,188,11,11,80,74,673,583
16,정선경찰서,1675,1509,19,21,230,197,181,168,370,327,12,10,107,93,756,693
17,철원경찰서,1125,948,19,15,96,47,134,130,250,175,12,12,56,54,558,515
18,화천경찰서,443,410,8,7,46,30,63,69,85,75,4,4,28,28,209,197
19,양구경찰서,559,469,14,9,63,43,69,63,101,87,6,6,32,28,274,233
20,인제경찰서,916,771,9,6,75,47,130,119,189,139,12,10,65,56,436,394
21,고성경찰서,1138,945,8,5,82,72,163,145,151,111,11,10,62,52,661,550

In [222]:
crime15.columns = crime15.iloc[1]
c1=crime15.copy()

In [223]:
del c1['강력범']
del c1['절도범']
del c1['폭력범']
del c1['지능범']
del c1['풍속범']
del c1['기타형사범']
del c1['특별법범']
c1

1    경찰서별     합계     합계
0    경찰서별   2015   2015
1    경찰서별     합계     합계
2    경찰서별     발생     검거
3      합계  56928  46673
4     강원청      0    478
5   춘천경찰서  10603   8162
6   원주경찰서  14088  11076
7   강릉경찰서   7634   6060
8   동해경찰서   3632   3060
9   태백경찰서   1484   1310
10  속초경찰서   4843   3928
11  삼척경찰서   2587   2179
12  홍천경찰서   2395   2176
13  횡성경찰서   1368   1059
14  영월경찰서   1038    896
15  평창경찰서   1400   1237
16  정선경찰서   1675   1509
17  철원경찰서   1125    948
18  화천경찰서    443    410
19  양구경찰서    559    469
20  인제경찰서    916    771
21  고성경찰서   1138    945

In [224]:
c0=c1.copy()

In [225]:
c0

1    경찰서별     합계     합계
0    경찰서별   2015   2015
1    경찰서별     합계     합계
2    경찰서별     발생     검거
3      합계  56928  46673
4     강원청      0    478
5   춘천경찰서  10603   8162
6   원주경찰서  14088  11076
7   강릉경찰서   7634   6060
8   동해경찰서   3632   3060
9   태백경찰서   1484   1310
10  속초경찰서   4843   3928
11  삼척경찰서   2587   2179
12  홍천경찰서   2395   2176
13  횡성경찰서   1368   1059
14  영월경찰서   1038    896
15  평창경찰서   1400   1237
16  정선경찰서   1675   1509
17  철원경찰서   1125    948
18  화천경찰서    443    410
19  양구경찰서    559    469
20  인제경찰서    916    771
21  고성경찰서   1138    945

In [226]:
c0.drop([0],inplace=True)
c0

1    경찰서별     합계     합계
1    경찰서별     합계     합계
2    경찰서별     발생     검거
3      합계  56928  46673
4     강원청      0    478
5   춘천경찰서  10603   8162
6   원주경찰서  14088  11076
7   강릉경찰서   7634   6060
8   동해경찰서   3632   3060
9   태백경찰서   1484   1310
10  속초경찰서   4843   3928
11  삼척경찰서   2587   2179
12  홍천경찰서   2395   2176
13  횡성경찰서   1368   1059
14  영월경찰서   1038    896
15  평창경찰서   1400   1237
16  정선경찰서   1675   1509
17  철원경찰서   1125    948
18  화천경찰서    443    410
19  양구경찰서    559    469
20  인제경찰서    916    771
21  고성경찰서   1138    945

In [227]:
c0.drop([1],inplace=True)
c0

1    경찰서별     합계     합계
2    경찰서별     발생     검거
3      합계  56928  46673
4     강원청      0    478
5   춘천경찰서  10603   8162
6   원주경찰서  14088  11076
7   강릉경찰서   7634   6060
8   동해경찰서   3632   3060
9   태백경찰서   1484   1310
10  속초경찰서   4843   3928
11  삼척경찰서   2587   2179
12  홍천경찰서   2395   2176
13  횡성경찰서   1368   1059
14  영월경찰서   1038    896
15  평창경찰서   1400   1237
16  정선경찰서   1675   1509
17  철원경찰서   1125    948
18  화천경찰서    443    410
19  양구경찰서    559    469
20  인제경찰서    916    771
21  고성경찰서   1138    945

In [228]:

c0.drop([3],inplace=True)
c0.drop([4],inplace=True)

In [229]:
c0.columns=c0.iloc[0]
c0.drop([2],inplace=True)

In [230]:
c0

2    경찰서별     발생     검거
5   춘천경찰서  10603   8162
6   원주경찰서  14088  11076
7   강릉경찰서   7634   6060
8   동해경찰서   3632   3060
9   태백경찰서   1484   1310
10  속초경찰서   4843   3928
11  삼척경찰서   2587   2179
12  홍천경찰서   2395   2176
13  횡성경찰서   1368   1059
14  영월경찰서   1038    896
15  평창경찰서   1400   1237
16  정선경찰서   1675   1509
17  철원경찰서   1125    948
18  화천경찰서    443    410
19  양구경찰서    559    469
20  인제경찰서    916    771
21  고성경찰서   1138    945

In [231]:
c1=c0.reset_index(drop=True)

In [232]:
c1

2    경찰서별     발생     검거
0   춘천경찰서  10603   8162
1   원주경찰서  14088  11076
2   강릉경찰서   7634   6060
3   동해경찰서   3632   3060
4   태백경찰서   1484   1310
5   속초경찰서   4843   3928
6   삼척경찰서   2587   2179
7   홍천경찰서   2395   2176
8   횡성경찰서   1368   1059
9   영월경찰서   1038    896
10  평창경찰서   1400   1237
11  정선경찰서   1675   1509
12  철원경찰서   1125    948
13  화천경찰서    443    410
14  양구경찰서    559    469
15  인제경찰서    916    771
16  고성경찰서   1138    945

In [233]:
c1['발생'].astype(str)
c1['검거'].astype(str)

0      8162
1     11076
2      6060
3      3060
4      1310
5      3928
6      2179
7      2176
8      1059
9       896
10     1237
11     1509
12      948
13      410
14      469
15      771
16      945
Name: 검거, dtype: object

In [234]:
c1['검거율']=c1['검거'].astype(int)/c1['발생'].astype(int)
c1

2    경찰서별     발생     검거       검거율
0   춘천경찰서  10603   8162  0.769782
1   원주경찰서  14088  11076  0.786201
2   강릉경찰서   7634   6060  0.793817
3   동해경찰서   3632   3060  0.842511
4   태백경찰서   1484   1310  0.882749
5   속초경찰서   4843   3928  0.811068
6   삼척경찰서   2587   2179  0.842288
7   홍천경찰서   2395   2176  0.908559
8   횡성경찰서   1368   1059  0.774123
9   영월경찰서   1038    896  0.863198
10  평창경찰서   1400   1237  0.883571
11  정선경찰서   1675   1509  0.900896
12  철원경찰서   1125    948  0.842667
13  화천경찰서    443    410  0.925508
14  양구경찰서    559    469  0.838998
15  인제경찰서    916    771  0.841703
16  고성경찰서   1138    945  0.830404

In [235]:
c2=c1['검거율']*100
c1['검거율(%)']=c2

In [236]:
del c1['검거율']

In [237]:
c2=c1['검거율(%)'].astype(int)

In [238]:
c1['검거율(%)']=c2

In [239]:
del c1['발생']
del c1['검거']

c1

2    경찰서별  검거율(%)
0   춘천경찰서      76
1   원주경찰서      78
2   강릉경찰서      79
3   동해경찰서      84
4   태백경찰서      88
5   속초경찰서      81
6   삼척경찰서      84
7   홍천경찰서      90
8   횡성경찰서      77
9   영월경찰서      86
10  평창경찰서      88
11  정선경찰서      90
12  철원경찰서      84
13  화천경찰서      92
14  양구경찰서      83
15  인제경찰서      84
16  고성경찰서      83

In [242]:
c_15=c1.copy()

In [243]:
c1

2    경찰서별  검거율(%)
0   춘천경찰서      76
1   원주경찰서      78
2   강릉경찰서      79
3   동해경찰서      84
4   태백경찰서      88
5   속초경찰서      81
6   삼척경찰서      84
7   홍천경찰서      90
8   횡성경찰서      77
9   영월경찰서      86
10  평창경찰서      88
11  정선경찰서      90
12  철원경찰서      84
13  화천경찰서      92
14  양구경찰서      83
15  인제경찰서      84
16  고성경찰서      83

# 2016년도 검거율

In [200]:
crime16 = pd.read_csv('crime16.csv', encoding = 'UTF-8', header=None)
crime16

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,경찰서별,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016
1,경찰서별,합계,합계,강력범,강력범,절도범,절도범,폭력범,폭력범,지능범,지능범,풍속범,풍속범,기타형사범,기타형사범,특별법범,특별법범
2,경찰서별,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
3,합계,58815,49509,706,671,5165,3568,10853,9841,8155,6832,229,188,3333,2987,30374,25422
4,강원청,0,951,0,89,0,9,0,53,0,368,0,3,0,26,0,403
5,춘천경찰서,11225,8820,127,105,1116,646,1818,1551,1314,997,39,35,672,506,6139,4980
6,원주경찰서,14933,12030,144,112,1311,923,2941,2646,2183,1519,50,39,759,648,7545,6143
7,강릉경찰서,7419,6025,108,96,762,469,1824,1595,1194,997,20,16,433,397,3078,2455
8,동해경찰서,3407,2947,47,37,178,143,703,680,362,314,17,10,193,195,1907,1568
9,태백경찰서,1528,1405,18,18,118,95,383,361,179,187,6,5,67,65,757,674
10,속초경찰서,4828,3990,61,54,392,276,932,854,516,432,22,20,331,312,2574,2042
11,삼척경찰서,3078,2587,27,24,225,141,585,520,365,329,12,11,159,153,1705,1409
12,홍천경찰서,2758,2396,41,39,203,184,420,414,442,356,10,9,160,166,1482,1228
13,횡성경찰서,1369,1183,17,17,128,112,181,164,158,117,5,5,76,72,804,696
14,영월경찰서,1063,904,16,7,69,53,151,147,125,115,11,10,60,46,631,526
15,평창경찰서,1475,1279,22,13,120,87,158,149,252,203,11,9,88,81,824,737
16,정선경찰서,1923,1642,26,19,240,188,210,199,377,293,7,6,118,100,945,837
17,철원경찰서,972,851,17,14,101,65,125,121,206,170,4,2,63,62,456,417
18,화천경찰서,517,447,4,3,43,33,92,84,90,78,0,0,30,34,258,215
19,양구경찰서,466,415,8,6,56,39,66,62,75,72,4,4,26,26,231,206
20,인제경찰서,869,784,6,6,50,25,133,122,154,121,3,3,50,52,473,455
21,고성경찰서,985,853,17,12,53,80,131,119,163,164,8,1,48,46,565,431

In [201]:
crime16.columns = crime16.iloc[1]
c1=crime16.copy()

In [202]:
del c1['강력범']
del c1['절도범']
del c1['폭력범']
del c1['지능범']
del c1['풍속범']
del c1['기타형사범']
del c1['특별법범']
c1

1    경찰서별     합계     합계
0    경찰서별   2016   2016
1    경찰서별     합계     합계
2    경찰서별     발생     검거
3      합계  58815  49509
4     강원청      0    951
5   춘천경찰서  11225   8820
6   원주경찰서  14933  12030
7   강릉경찰서   7419   6025
8   동해경찰서   3407   2947
9   태백경찰서   1528   1405
10  속초경찰서   4828   3990
11  삼척경찰서   3078   2587
12  홍천경찰서   2758   2396
13  횡성경찰서   1369   1183
14  영월경찰서   1063    904
15  평창경찰서   1475   1279
16  정선경찰서   1923   1642
17  철원경찰서    972    851
18  화천경찰서    517    447
19  양구경찰서    466    415
20  인제경찰서    869    784
21  고성경찰서    985    853

In [203]:
c0=c1.copy()

In [204]:
c0.drop([0],inplace=True)
c0.drop([1],inplace=True)
c0.drop([3],inplace=True)
c0.drop([4],inplace=True)

In [205]:
c0

1    경찰서별     합계     합계
2    경찰서별     발생     검거
5   춘천경찰서  11225   8820
6   원주경찰서  14933  12030
7   강릉경찰서   7419   6025
8   동해경찰서   3407   2947
9   태백경찰서   1528   1405
10  속초경찰서   4828   3990
11  삼척경찰서   3078   2587
12  홍천경찰서   2758   2396
13  횡성경찰서   1369   1183
14  영월경찰서   1063    904
15  평창경찰서   1475   1279
16  정선경찰서   1923   1642
17  철원경찰서    972    851
18  화천경찰서    517    447
19  양구경찰서    466    415
20  인제경찰서    869    784
21  고성경찰서    985    853

In [206]:
c0.columns=c0.iloc[0]
c0.drop([2],inplace=True)

In [207]:
c0

2    경찰서별     발생     검거
5   춘천경찰서  11225   8820
6   원주경찰서  14933  12030
7   강릉경찰서   7419   6025
8   동해경찰서   3407   2947
9   태백경찰서   1528   1405
10  속초경찰서   4828   3990
11  삼척경찰서   3078   2587
12  홍천경찰서   2758   2396
13  횡성경찰서   1369   1183
14  영월경찰서   1063    904
15  평창경찰서   1475   1279
16  정선경찰서   1923   1642
17  철원경찰서    972    851
18  화천경찰서    517    447
19  양구경찰서    466    415
20  인제경찰서    869    784
21  고성경찰서    985    853

In [208]:
c1=c0.reset_index(drop=True)

In [209]:
c1['검거율']=c1['검거'].astype(int)/c1['발생'].astype(int)
c1

2    경찰서별     발생     검거       검거율
0   춘천경찰서  11225   8820  0.785746
1   원주경찰서  14933  12030  0.805598
2   강릉경찰서   7419   6025  0.812104
3   동해경찰서   3407   2947  0.864984
4   태백경찰서   1528   1405  0.919503
5   속초경찰서   4828   3990  0.826429
6   삼척경찰서   3078   2587  0.840481
7   홍천경찰서   2758   2396  0.868745
8   횡성경찰서   1369   1183  0.864134
9   영월경찰서   1063    904  0.850423
10  평창경찰서   1475   1279  0.867119
11  정선경찰서   1923   1642  0.853874
12  철원경찰서    972    851  0.875514
13  화천경찰서    517    447  0.864603
14  양구경찰서    466    415  0.890558
15  인제경찰서    869    784  0.902186
16  고성경찰서    985    853  0.865990

In [210]:
c2=c1['검거율']*100
c1['검거율(%)']=c2

In [211]:
del c1['검거율']

In [212]:
c2=c1['검거율(%)'].astype(int)

In [214]:
c1['검거율(%)']=c2

In [215]:
del c1['발생']
del c1['검거']

2    경찰서별  검거율(%)
0   춘천경찰서      78
1   원주경찰서      80
2   강릉경찰서      81
3   동해경찰서      86
4   태백경찰서      91
5   속초경찰서      82
6   삼척경찰서      84
7   홍천경찰서      86
8   횡성경찰서      86
9   영월경찰서      85
10  평창경찰서      86
11  정선경찰서      85
12  철원경찰서      87
13  화천경찰서      86
14  양구경찰서      89
15  인제경찰서      90
16  고성경찰서      86

In [218]:
c_16=c1.copy()

In [244]:
c_15

2    경찰서별  검거율(%)
0   춘천경찰서      76
1   원주경찰서      78
2   강릉경찰서      79
3   동해경찰서      84
4   태백경찰서      88
5   속초경찰서      81
6   삼척경찰서      84
7   홍천경찰서      90
8   횡성경찰서      77
9   영월경찰서      86
10  평창경찰서      88
11  정선경찰서      90
12  철원경찰서      84
13  화천경찰서      92
14  양구경찰서      83
15  인제경찰서      84
16  고성경찰서      83

In [246]:
c_16['평균 검거율']=(c_16['검거율(%)']+c_15['검거율(%)'])/2

In [248]:
del c_16['검거율(%)']
c_16

2    경찰서별  평균 검거율
0   춘천경찰서    77.0
1   원주경찰서    79.0
2   강릉경찰서    80.0
3   동해경찰서    85.0
4   태백경찰서    89.5
5   속초경찰서    81.5
6   삼척경찰서    84.0
7   홍천경찰서    88.0
8   횡성경찰서    81.5
9   영월경찰서    85.5
10  평창경찰서    87.0
11  정선경찰서    87.5
12  철원경찰서    85.5
13  화천경찰서    89.0
14  양구경찰서    86.0
15  인제경찰서    87.0
16  고성경찰서    84.5

In [249]:
crime=c_16.copy()

In [250]:
crime

2    경찰서별  평균 검거율
0   춘천경찰서    77.0
1   원주경찰서    79.0
2   강릉경찰서    80.0
3   동해경찰서    85.0
4   태백경찰서    89.5
5   속초경찰서    81.5
6   삼척경찰서    84.0
7   홍천경찰서    88.0
8   횡성경찰서    81.5
9   영월경찰서    85.5
10  평창경찰서    87.0
11  정선경찰서    87.5
12  철원경찰서    85.5
13  화천경찰서    89.0
14  양구경찰서    86.0
15  인제경찰서    87.0
16  고성경찰서    84.5